### ISSUE TITLE
Wrong colorization after )> combination

### ISSUE THREAD

**Issue by alfonsogarciacaro** [ionide/ionide-fsgrammar#102] opened 2018-09-20 12:58 UTC
```fsharp
let inline create<'a, 'b when 'a :> ICreator<'b> and 'a: (new: unit -> 'a)> () : 'b =  ((new 'a()).Make())
```

![colorization](https://user-images.githubusercontent.com/8275461/45819813-9483d300-bce5-11e8-8e09-72b72dd23719.gif)

**Comment by MangelMaxime** [comment] 2018-09-20 14:53
I need to do more test but I think the source of the problem is `:>`. The `>` is closing the generic declaration.

Because if I remove it then the syntax coloration is better. Still not perfect because I forgot to add support for SRTP.

<img width="649" alt="capture d ecran 2018-09-20 a 16 53 05" src="https://user-images.githubusercontent.com/4760796/45826957-c309aa00-bcf5-11e8-992e-d8d105c37d9d.png">

**Comment by MangelMaxime** [comment] 2018-09-20 14:58
Oops, my screenshot is pretty bad... But note the color different color of `failwith` :)

**Closed** 2018-10-18 10:09 UTC
