### ISSUE TITLE
let f = (*) 2 is highlighted as a comment

### ISSUE THREAD

**Issue by ihavenonickname** [ionide/ionide-fsgrammar#161] opened 2021-11-25 02:19 UTC
**Describe the bug**
Using the multiplication operator as a prefix function (i.e. `(*)`) is highlighted as a comment.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a `.fs` file
1. Write `let double = (*) 2`
1. the `*)` is wrongly highlighted as comment

**Expected behaviour**
It should be highlighted as a regular prefix operator, such as `(+)`

**Screenshots**
![screenshot](https://i.imgur.com/Fbemdrs.png)

**Environment**
 - OS: Windows 10
 - VSCode version: 1.62.3

**Comment by MangelMaxime** [comment] 2021-11-25 10:52
Hum, 
I suppose this is because comments rules are placed before keywords rules like way highter...

Comments rules are at rank 2 while keywords rules are 16. 

I am unsure if we can change the rank easily without breaking stuff.

**Comment by rdipardo** [comment] 2021-11-28 14:30
> I am unsure if we can change the rank easily without breaking stuff.

I think all you need is a better regex. The `"begin"` pattern is already correct: it won't allow a closing paren right after the opening `(*`:

![regex101-ni-match-begin](https://user-images.githubusercontent.com/59004801/143771570-4f9903cb-5ee2-44e5-aafc-e506d0e5b4f4.png)

The problem is that the `"end"` pattern is too permissive:

![regex101-match-end](https://user-images.githubusercontent.com/59004801/143771349-152bd3a0-97c6-441a-bd45-18db413721a2.png)

It's just a matter of making the `"end"` pattern symmetrical with `"begin"`, like this:

```diff
diff --git a/grammars/fsharp.json b/grammars/fsharp.json
index 3c70cb8..527d097 100644
--- a/grammars/fsharp.json
+++ b/grammars/fsharp.json
@@ -547,7 +547,7 @@
                 {
                     "name": "comment.block.fsharp",
                     "begin": "(\\(\\*(?!\\)))",
-                    "end": "(\\*\\))",
+                    "end": "((?<!\\()\\*\\))",
                     "beginCaptures": {
                         "1": {
                             "name": "comment.block.fsharp"
@@ -571,7 +571,7 @@
                 },
                 {
                     "name": "comment.block.markdown.fsharp.end",
-                    "match": "((\\*)+\\))",
+                    "match": "(((?<!\\()\\*)+\\))",
                     "captures": {
                         "1": {
                             "name": "comment.block.fsharp"

````

I tried it locally and it works:

![sample-code-patched](https://user-images.githubusercontent.com/59004801/143771630-8581039c-74ce-45cf-aea1-3f81f408733f.png)

**Comment by MangelMaxime** [comment] 2021-11-29 20:54
PR #162 fix this specific issue.

However, it doesn't cover cases like `(****)` because the negative look ahead need to have a fixed length.

**Closed** 2021-11-29 23:24 UTC
